all:
  children:
    infra:
      hosts:
        pi-1:
          ansible_host: 192.168.1.10
        pi-2:
          ansible_host: 192.168.1.11

    apps:
      hosts:
        pi-3:
          ansible_host: 192.168.1.12
